### ISSUE TITLE
MCreator 2023.2 support

### ISSUE THREAD

**Issue by Fenris42** [NerdyPuzzle/Just-enough-recipes-MCreator#1]
I would like to use your plugin but im working on a mod for Minecraft 1.19.2 which is unfortunately capped at MCreator 2023.2. Would it be possible to compile a version of JER for this MCreator version please?

**Comment by NerdyPuzzle** [comment]
JER supports 1.19.2 if you use the 1.19.2 generator plugin

**Comment by Fenris42** [comment]
Oh thank you. Im very new to this and didnt know that existed. I was very confused why MCreator only supported the 2 most recent versions
