### ISSUE TITLE
Custom recipes doesn't work on the new JEI versions.

### ISSUE THREAD

**Issue by ArkyFursblack** [NerdyPuzzle/Just-enough-recipes-MCreator#4]
Custom JEI recipe types doesn't work on the new JEI versions higher than 15.2.0.27.

**Comment by NerdyPuzzle** [comment]
Please elaborate further. Do the recipes not show up in jei, or does the procedure for getting the recipe result not work?

**Comment by ArkyFursblack** [comment]
No it's not about procedure. I made a custom JEI recipe type and a lot of recipes for it. But I can't see this recipes using new versions of JEI. Plugin uses JEI 15.2.0.27 so I think that it's because some changes in new versions of the mod.

**Comment by NerdyPuzzle** [comment]
I'll check it out once Im free

**Comment by NerdyPuzzle** [comment]
After updating the JEI version the plugin uses, the problem seems to not exist? This is probably just some imports changing and will solve itself once you use the latest plugin version.

**Comment by ArkyFursblack** [comment]
I still can't see custom recipes in JEI. You just updated the JEI version in MCreator but the problem isn't solved. It impossible to see the crafts even in mcreator test environment. The problem is that I can't see custom recipes and recipes types at all in game.

**Comment by NerdyPuzzle** [comment]
Then the issue is something else. Run the client from mcreator, open a world, and copy everything in the console, there should be some indication of what's wrong there.

**Comment by ArkyFursblack** [comment]
but everything works on the version 15.2.0.27 and below. 

anyway there's a console.
[console.txt](https://github.com/user-attachments/files/15944924/console.txt)

**Comment by NerdyPuzzle** [comment]
Log says you tried to use air as the recipe category icon...

**Comment by ArkyFursblack** [comment]
But it was working with old version of JEI. And not all the recipes uses air as icon.

**Comment by ArkyFursblack** [comment]
oh ok I changed icons with air and everything start to work. JEI was working even with air in previous versions but now it don't but anyway I have fixed my mod.
