### ISSUE TITLE
Information Tab showing data, not present in element

### ISSUE THREAD

**Issue by smmmadden** [NerdyPuzzle/Just-enough-recipes-MCreator#5]
I created an information tab for one of my items and it is showing "6" before Add coin sentence which doesn't exist in the element itself.  Here you can see the configuration for it and it doesn't match.  Looks like the Minecraft color codes are not translating correctly at first sight, but even removing it, I have the **6** still present.
**Configuration**
![image](https://github.com/NerdyPuzzle/Just-enough-recipes-MCreator/assets/10309346/d146d9da-df03-44ea-85f1-361b560739f8)

**JEI Hover over Coin**
![image](https://github.com/NerdyPuzzle/Just-enough-recipes-MCreator/assets/10309346/e0367a6a-aa1b-4ff5-a8f1-ea8ccb994dc9)

**Crafting Table hover**
![image](https://github.com/NerdyPuzzle/Just-enough-recipes-MCreator/assets/10309346/501beefa-df9f-469d-9e1a-177ef99fea3a)

**Crafted Coin hover**
![image](https://github.com/NerdyPuzzle/Just-enough-recipes-MCreator/assets/10309346/6f06d03d-73cf-4bb6-bcb8-6082132441dc)

**Removed color codes from 2nd/3rd row - and from all rows**
![image](https://github.com/NerdyPuzzle/Just-enough-recipes-MCreator/assets/10309346/8d449e7a-5b50-48cf-8233-366214ff53c2)

As shown here, the JEI Tab itself looks fine.  There is no 6 showing in the display, just the hovers.  To be clear, I'm not expecting color in the hovers (don't believe that is supported), but the extra character that isn't present in the configuration that is a bug.  Seems like it is cached somewhere and not getting updated if it changed.
![image](https://github.com/NerdyPuzzle/Just-enough-recipes-MCreator/assets/10309346/fd526c1a-368d-4799-9286-37e5bde4a59c)

**Comment by NerdyPuzzle** [comment]
Jei information creates a translation key, you should be able to find it in localisation and edit it, though I don't know why it wouldn't automatically update...

**Comment by smmmadden** [comment]
I did a search in the entire workspace folder and found one file \workspaces\oresandmore\elements\GoldCoin.mod.json and removed the 6 in it.  It still shows in-game.
Tried removing the entire row in the element and re-added it and still showed in-game.
Then I deleted the GoldCoin JEI element in MCreator and created GoldCoins JEI element.  I also changed the row where it says 6 Gold Coins are crafted...to Six Gold coins are crafted thinking maybe it got replicated in the next row.  In-game, I still see the 6 in both rows, so whereever the hover text is getting stored, it isn't getting updated and I cannot find any references in the workspace to manually edit it. :-(

**Comment by NerdyPuzzle** [comment]
Look for the localisation tab on the left side

**Comment by smmmadden** [comment]
ah, never looked there before.  Good to know! :-)
Unfortunately, it looks fine here.
![image](https://github.com/NerdyPuzzle/Just-enough-recipes-MCreator/assets/10309346/de388c0b-644e-40e9-9931-0166d709ff1b)

**Comment by NerdyPuzzle** [comment]
Then I don't know what's happening, maybe jei stores information somewhere or something, because the translation key is what's used by the item information element.

**Comment by smmmadden** [comment]
it is a weird one.  There doesn't appear to be any file in the workspace holding on to it that is "searchable", so it may be worth it to reach out to JEI developers to see what's going on.  Could be a bug on their end?

**Comment by NerdyPuzzle** [comment]
I can't do anything about this
