### ISSUE TITLE
[Mod]ModTabs does not exist

### ISSUE THREAD

**Issue by Jagger223** [NerdyPuzzle/Just-enough-recipes-MCreator#6]
This is what the console looks like:

`> Task :writeMinecraftClasspathJunit UP-TO-DATE 
> Task :compileJava 
C:\Users\TJ\MCreatorWorkspaces\too_many_recipes\src\main\java\net\mcreator\tmrme\init\TheMostRandomestModEverModRecipeTypes.java:22: warning: [removal] FMLJavaModLoadingContext in net.neoforged.fml.javafmlmod has been deprecated and marked for removal 
        IEventBus bus = FMLJavaModLoadingContext.get().getModEventBus(); 
                        ^ 
[C:\Users\TJ\MCreatorWorkspaces\too_many_recipes\src\main\java\net\mcreator\tmrme\TheMostRandomestModEverMod.java:56](file:///C:/Users/TJ/MCreatorWorkspaces/too_many_recipes/src/main/java/net/mcreator/tmrme/TheMostRandomestModEverMod.java:56): error: package TheMostRandomestModEverModTabs does not exist 
        TheMostRandomestModEverModTabs.REGISTRY.register(modEventBus); 
                                      ^ 
1 error 
1 warning 
> Task :compileJava FAILED`

I have tried manually removing the section of code from the java file referenced. The code then reset after i tried to run it again (this is probably a problem with MCreator, not your plugin. I also did save it).

Within the java code, ModTabs is only referenced once. That could possibly be the cause of the issue on my end. This is not likely however as I have very little skill in the Java language.

**Comment by NerdyPuzzle** [comment]
The code that causes an error is completely unrelated to this plugin.
